force-app/main/default/objects/Task__c/Task__c.object-meta.xml
<CustomObject>
    <description>Daily, Weekly and Monthly task</description>
    <label>User Task</label>
    <nameField>
        <label>Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>User Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Task__c/fields/Assigned_User__c.field-meta.xml
<CustomField>
    <fullName>Assigned_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned User</label>
    <referenceTo>User_Master__c</referenceTo>
    <relationshipLabel>User Tasks (Assigned User)</relationshipLabel>
    <relationshipName>Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Task__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cooking</fullName>
            </value>
            <value>
                <fullName>Cleaning</fullName>
            </value>
            <value>
                <fullName>Bill Payments</fullName>
            </value>
            <value>
                <fullName>Sending Money</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Task__c/fields/Re_assign_to__c.field-meta.xml
<CustomField>
    <fullName>Re_assign_to__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Re-assign to</label>
    <referenceTo>User_Master__c</referenceTo>
    <relationshipName>Tasks1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Task__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Incomplete</fullName>
            </value>
            <value>
                <fullName>Reassigned</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Assigned</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Task__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Category__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Floor</fullName>
            </value>
            <value>
                <fullName>Kitchen</fullName>
            </value>
            <value>
                <fullName>Washrroom</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
            <value>
                <fullName>Rent Payment</fullName>
            </value>
            <value>
                <fullName>Pending Dues</fullName>
            </value>
            <value>
                <fullName>Electric Bill</fullName>
            </value>
            <value>
                <fullName>Water Bill</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User_Master__c/User_Master__c.object-meta.xml
<CustomObject>
    <description>List of user masters</description>
    <label>User Master</label>
    <nameField>
        <label>User Master Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>User Masters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Master__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <defaultValue>&quot;@gmail.com&quot;</defaultValue>
    <description>Email of the User</description>
    <label>Email</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/User_Master__c/fields/Office_Mail__c.field-meta.xml
<CustomField>
    <fullName>Office_Mail__c</fullName>
    <label>Office Mail</label>
    <type>Email</type>
</CustomField>

force-app/main/default/classes/OpenTaskMailFormat_Controller.cls
public class OpenTaskMailFormat_Controller {
    
    public Id uID {get;set;}
    public List<Task__c> tasks {
        get{
            tasks = [SELECT  Id, Name, Category__c, Deadline__c, Re_assign_to__c, Assigned_User__c, Status__c, Type__c, Additional_Comments__c
                     FROM Task__c
                     WHERE (Assigned_User__c =: uID OR Re_assign_to__c =: uID ) AND Status__c != 'Completed'];
            return tasks;
        }set;
    }
    Public User_Master__c usr {
        get{
            usr = [SELECT Id, Name, Email__c, Office_Mail__c
                   FROM User_Master__c
                   WHERE Id =:  uID];
            return usr;
        }set;
    }
}