force-app/main/default/objects/Loan_and_Dues__c/Loan_and_Dues__c.object-meta.xml
<CustomObject>
    <label>Loan and Dues</label>
    <nameField>
        <displayFormat>Dues-{000}</displayFormat>
        <label>Dues Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loans and Dues</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Loan_and_Dues__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>8</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Loan_and_Dues__c/fields/Comments__c.field-meta.xml
<CustomField>
    <fullName>Comments__c</fullName>
    <label>Comments / Reason</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Loan_and_Dues__c/fields/Due_type__c.field-meta.xml
<CustomField>
    <fullName>Due_type__c</fullName>
    <defaultValue>&quot;Owe to&quot;</defaultValue>
    <label>Due type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Owe to</fullName>
            </value>
            <value>
                <fullName>Pending with</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Loan_and_Dues__c/fields/Paid_date__c.field-meta.xml
<CustomField>
    <fullName>Paid_date__c</fullName>
    <defaultValue>Today()</defaultValue>
    <label>Paid date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Loan_and_Dues__c/fields/Person_Name__c.field-meta.xml
<CustomField>
    <fullName>Person_Name__c</fullName>
    <label>Person Name</label>
    <referenceTo>User_Master__c</referenceTo>
    <relationshipLabel>Loans and Dues</relationshipLabel>
    <relationshipName>Loans_and_Dues</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Loan_and_Dues__c/fields/Secondary_User__c.field-meta.xml
<CustomField>
    <fullName>Secondary_User__c</fullName>
    <label>Secondary User</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Loan_and_Dues__c/fields/Settled_date__c.field-meta.xml
<CustomField>
    <fullName>Settled_date__c</fullName>
    <label>Settled Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Loan_and_Dues__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&quot;Pending&quot;</defaultValue>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Share__c/Share__c.object-meta.xml
<CustomObject>
    <description>Shares between user master</description>
    <label>Share</label>
    <nameField>
        <label>Shares Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shares</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Share__c/fields/Monthly_Expence__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Expence__c</fullName>
    <label>Monthly Expence</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Share__c/fields/Total_Expense__c.field-meta.xml
<CustomField>
    <fullName>Total_Expense__c</fullName>
    <label>Total Expense</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Task__c/Task__c.object-meta.xml
<CustomObject>
    <description>Daily, Weekly and Monthly task</description>
    <label>User Task</label>
    <nameField>
        <label>Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>User Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Task__c/fields/Assigned_User__c.field-meta.xml
<CustomField>
    <fullName>Assigned_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned User</label>
    <referenceTo>User_Master__c</referenceTo>
    <relationshipLabel>User Tasks (Assigned User)</relationshipLabel>
    <relationshipName>Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Task__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cooking</fullName>
            </value>
            <value>
                <fullName>Cleaning</fullName>
            </value>
            <value>
                <fullName>Bill Payments</fullName>
            </value>
            <value>
                <fullName>Sending Money</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Task__c/fields/Re_assign_to__c.field-meta.xml
<CustomField>
    <fullName>Re_assign_to__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Re-assign to</label>
    <referenceTo>User_Master__c</referenceTo>
    <relationshipName>Tasks1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Task__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Incomplete</fullName>
            </value>
            <value>
                <fullName>Reassigned</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Assigned</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Task__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Category__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Floor</fullName>
            </value>
            <value>
                <fullName>Kitchen</fullName>
            </value>
            <value>
                <fullName>Washrroom</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
            <value>
                <fullName>Rent Payment</fullName>
            </value>
            <value>
                <fullName>Pending Dues</fullName>
            </value>
            <value>
                <fullName>Electric Bill</fullName>
            </value>
            <value>
                <fullName>Water Bill</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User_Master__c/User_Master__c.object-meta.xml
<CustomObject>
    <description>List of user masters</description>
    <label>User Master</label>
    <nameField>
        <label>User Master Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>User Masters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Master__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <defaultValue>&quot;@gmail.com&quot;</defaultValue>
    <description>Email of the User</description>
    <label>Email</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/User_Master__c/fields/To_Get__c.field-meta.xml
<CustomField>
    <fullName>To_Get__c</fullName>
    <label>To Get</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/User_Master__c/fields/To_Pay__c.field-meta.xml
<CustomField>
    <fullName>To_Pay__c</fullName>
    <label>To Pay</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/User_Master__c/fields/Total_Amount_Shared__c.field-meta.xml
<CustomField>
    <fullName>Total_Amount_Shared__c</fullName>
    <label>Total Amount Shared</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/User_Master__c/fields/Total_Amount_Spent__c.field-meta.xml
<CustomField>
    <fullName>Total_Amount_Spent__c</fullName>
    <label>Total Amount Spent(Current Month)</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/User_Master__c/fields/Total_Expence__c.field-meta.xml
<CustomField>
    <fullName>Total_Expence__c</fullName>
    <label>Total Expence</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/ScheduledTask.cls
public class ScheduledTask {
    public static void dailyRun(){
        
        //Todays date
        Date tday = Date.today();
        
        Integer thisMonth = System.Today().Month();
        
        //Getting Previous Month
        Integer previousMonth = System.Today().Month() - 1; //To get The previous month as Number
        
        
        
        
        //For January
        if(previousMonth == 0){
            previousMonth = 12;
        }
        
        //Current day of month
        Integer dayOfMnth = System.Today().day(); 	//returns day of the Month ie. 1 for 1st of month
        
        //Listing all users
        List<User_Master__c> users = [SELECT Id, Name, Total_Expence__c, Total_Amount_Shared__c, Total_Amount_Spent__c, To_Get__c, To_Pay__c, Email__c
                                      FROM User_Master__c
                                     ];
        //if(dayOfMnth == 1){
            List<Share__c> createdShare = new List<Share__c>();
            try{
                createdShare = [SELECT Id, Monthly_Expence__c, Total_Expense__c 
                                FROM share__c
                                WHERE CALENDAR_MONTH(createdDate) =: thisMonth AND CALENDAR_YEAR(createdDate) = 2019 LIMIT 1];
            }catch(Exception ex){
                system.debug('Null Pointer'+ex.getMessage());
            }
            if(createdShare.isEmpty()){
                TaskAndProgress.monthlyTask('Monthly');
                Share__c share= new Share__c();
                Share__c oldShare= [SELECT Id, Monthly_Expence__c, Total_Expense__c 
                                    FROM share__c
                                    WHERE CALENDAR_MONTH(createdDate) =: previousMonth ORDER BY createdDate desc LIMIT 1];
                
                for(User_Master__c usr: users){
                    usr.Total_Amount_Shared__c = 0;
                    usr.Total_Amount_Spent__c = 0;
                    System.debug(usr);
                    update usr;
                }
                Datetime myDatetime = Datetime.now();
                String ShareName = 'Shares - '+myDatetime.format('MMMM d,  yyyy');
                System.debug(ShareName);
                share.Name =ShareName;
                share.Monthly_Expence__c = 0;
                share.Total_Expense__c = oldShare.Total_Expense__c;
                system.debug(share);
                insert share;
                try{
                    SendEmail.sendEmailOnSharesRefresh();
                }catch(Exception ex){
                    system.debug(ex.getMessage());
                }
            }
        /*else*/ if(dayOfMnth == 15){
            TaskAndProgress.billPaymentTask(tday);
        }
        
        if('sun'=='moon'){
            Datetime dt = (DateTime)tday;
            String dayOfWeek = dt.format('EEEE');
            if(dayOfWeek == 'Thursday'){
                TaskAndProgress.createNewTask('Weekly');
                SendEmail.sendACleaningReminder();
            }
            else if(dayOfWeek == 'Friday'){
                SendEmail.sendACleaningReminder();
            }else if(dayOfWeek == 'Saturday'){
                SendEmail.sendACleaningReminder();
            }
            //For Scheduled Reminders about paying and Getting Dues
            String formatedToday = tday.format();
            List<Loan_and_Dues__c> loan = [SELECT Id, Person_Name__c, Due_type__c, Amount__c, Paid_date__c, Due_Date__c, Status__c, Comments__c, Secondary_User__c, Settled_date__c FROM Loan_and_Dues__c];
            for(Loan_and_Dues__c singleLoan : loan){
                String DueDate = singleLoan.Due_Date__c.format();
                if(formatedToday == DueDate){
                    system.debug('Today '+formatedToday+' Due Date '+DueDate);
                    //send email calling Method
                    try{
                        SendEmail.DueAmountReminder(singleLoan.Id);
                    }
                    catch(Exception ex){
                        system.debug(ex.getMessage());
                    }
                }
            }
        }
        
        /*List<Task__c> tsks = [SELECT Id, Name, Additional_Comments__c, Assigned_User__r.Name, Assigned_User__c, Category__c, Deadline__c,
                                 Re_assign_to__c, Re_assign_to__r.Name, Status__c, Type__c
                                 FROM Task__c
                                 WHERE Status__c!='Completed'];
            Map<String,List<Task__c>> userTask = new Map<String,List<Task__c>>();
            for(Task__c eachTask: tsks){
                String taskMember;
                if(eachTask.Assigned_User__c != null){
                    taskMember = eachTask.Assigned_User__r.Name;
                }else{
                    taskMember = eachTask.Re_assign_to__r.Name;        
                }
                if(userTask.containsKey(taskMember)){
                    userTask.get(taskMember).add(eachTask);
                }else{
                    userTask.put(taskMember,new List<Task__c>());
                    userTask.get(taskMember).add(eachTask);
                }
                system.debug('UserTask MAP '+userTask);
            }
            
            for(String eachUser : userTask.keySet()){
                List<Task__c> temp = userTask.get(eachUser);
                if(temp != null){
                    Calculations.sendEmail(eachUser);
                }
                system.debug('User and Task'+' User '+eachUser+' Tasks '+temp);
                //sendEmail
            }
           
        }*/
    }
    
    public static void openTasks(){
        List<Task__c> tasks = [SELECT Id, Name, Deadline__c, Status__c, Category__c, Additional_Comments__c, Assigned_User__c, 
                               Re_assign_to__c, Type__c
                               FROM Task__c
                               WHERE Status__c !=  'Completed'];
        List<User_Master__c> users = [SELECT Id, Name, Total_Expence__c, Total_Amount_Shared__c, Total_Amount_Spent__c, 
                                      To_Get__c, To_Pay__c, Email__c
                                      FROM User_Master__c
                                     ];
        Map<Id,List<Task__c>> userTasks = new Map<Id,List<Task__c>>();
        for(Task__c tsk : tasks){
            Id user;
            if(tsk.Assigned_User__c != null){
                user = tsk.Assigned_User__c;
            }else{
                user = tsk.Re_assign_to__c;
            }
            system.debug('User '+ users.get(2));
            
            if(!userTasks.containsKey(user)){
                userTasks.put(user, new List<Task__c>());
                userTasks.get(user).add(tsk);
            }else{
                userTasks.get(user).add(tsk);
            }
        }
        System.debug(' Map of Tasks : '+userTasks);
        
        
        for(Id eachUser : userTasks.keySet()){
            List<Task__c> temp = userTasks.get(eachUser);
            if(temp != null){
                Calculations.sendEmail(eachUser);
            }
            system.debug('User and Task'+' User '+eachUser+' Tasks '+temp);
            //sendEmail
        }
        
        //User Specific List of Tasks
        /*for(User_Master__c usr : users){
            if(userTasks.containsKey(usr.Id)){
                system.debug('Count of tasks for '+usr.Name+' : '+userTasks.get(usr.Id).size());   
                List<Task__c> tsks = userTasks.get(usr.Id); 
                for(Integer i =0 ;i<tsks.size();i++){
                    system.debug('Task Name  : '+tsks[i].Name);
                }
            }
            
        }*/
                     
        
    }
    
}