force-app/main/default/objects/Loan_and_Dues__c/Loan_and_Dues__c.object-meta.xml
<CustomObject>
    <label>Loan and Dues</label>
    <nameField>
        <displayFormat>Dues-{000}</displayFormat>
        <label>Dues Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loans and Dues</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Loan_and_Dues__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>8</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Loan_and_Dues__c/fields/Due_type__c.field-meta.xml
<CustomField>
    <fullName>Due_type__c</fullName>
    <defaultValue>&quot;Owe to&quot;</defaultValue>
    <label>Due type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Owe to</fullName>
            </value>
            <value>
                <fullName>Pending with</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Loan_and_Dues__c/fields/Person_Name__c.field-meta.xml
<CustomField>
    <fullName>Person_Name__c</fullName>
    <label>Person Name</label>
    <referenceTo>User_Master__c</referenceTo>
    <relationshipLabel>Loans and Dues</relationshipLabel>
    <relationshipName>Loans_and_Dues</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Loan_and_Dues__c/fields/Settled_date__c.field-meta.xml
<CustomField>
    <fullName>Settled_date__c</fullName>
    <label>Settled Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Loan_and_Dues__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&quot;Pending&quot;</defaultValue>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Personal_User_Profile__c/Personal_User_Profile__c.object-meta.xml
<CustomObject>
    <label>Personal User Profile</label>
    <nameField>
        <label>Personal User Profile Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Personal User Profile</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Personal_User_Profile__c/fields/Master__c.field-meta.xml
<CustomField>
    <fullName>Master__c</fullName>
    <label>User Master</label>
    <referenceTo>User_Master__c</referenceTo>
    <relationshipLabel>Personal User Profile</relationshipLabel>
    <relationshipName>Personal_User_Profile</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/duesUpdates.cls
public class duesUpdates {
    public static void updatePersonalProfile(Loan_and_Dues__c dues){
        Personal_User_Profile__c usr = [Select Id, Name, To_Pay__c, To_Get__c
                                        FROM Personal_User_Profile__c
                                        WHERE Master__c =: dues.Person_Name__c];
        if(dues.Status__c == 'Pending'){
            if(dues.Due_type__c=='Owe to'){
                usr.To_Pay__c = usr.To_Pay__c + dues.Amount__c;
            }
            else if(dues.Due_type__c =='Pending with'){
                usr.To_Get__c = usr.To_Get__c + dues.Amount__c;
            }
        }
        else if(dues.Status__c == 'Paid'){
            if(dues.Due_type__c=='Owe to'){
                usr.To_Pay__c = usr.To_Pay__c - dues.Amount__c;
            }
            else if(dues.Due_type__c =='Pending with'){
                usr.To_Get__c = usr.To_Get__c - dues.Amount__c;
            }
            
            dues.Settled_date__c = DateTime.now();
        }
        update usr;
    }
}