force-app/main/default/objects/Expense__c/Expense__c.object-meta.xml
<CustomObject>
    <description>Expenses everyday</description>
    <label>Expense</label>
    <nameField>
        <label>Expence Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Expenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Expense__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <description>The Amount or Sum Spent on the Expense</description>
    <label>Amount</label>
    <precision>7</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/sampleDemoClass.cls
public class sampleDemoClass {
    public static void sampleMethod(){
        List<sObject> samIns = new List<sObject>();
        
        Account acc = new Account(name='Test');
        Insert acc;
        
        List<sObject> staIns = [SELECT Id, Name from Account];
        String dynQuery = 'SELECT Id, Name from Account ';
        samIns = Database.query(dynQuery);
        Expense__c ex = [Select Name, Amount__c from Expense__c limit 1];
        ex.Amount__c = 10000;
        Update ex;
        system.debug('Test');
        
    }
}