force-app/main/default/objects/Expense__c/Expense__c.object-meta.xml
<CustomObject>
    <description>Expenses everyday</description>
    <label>Expense</label>
    <nameField>
        <label>Expence Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Expenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Expense__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <description>The Amount or Sum Spent on the Expense</description>
    <label>Amount</label>
    <precision>7</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Expense__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <description>Category of expense</description>
    <inlineHelpText>Select a specific Category, If not listed please select other and add comments.</inlineHelpText>
    <label>Category</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Rent</fullName>
            </value>
            <value>
                <fullName>Advance</fullName>
            </value>
            <value>
                <fullName>Vegetables</fullName>
            </value>
            <value>
                <fullName>Non Veg</fullName>
            </value>
            <value>
                <fullName>Dairy Eggs Batter</fullName>
            </value>
            <value>
                <fullName>Internet/Wi-Fi</fullName>
            </value>
            <value>
                <fullName>Water</fullName>
            </value>
            <value>
                <fullName>Groceries</fullName>
            </value>
            <value>
                <fullName>Bike</fullName>
            </value>
            <value>
                <fullName>Snacks</fullName>
            </value>
            <value>
                <fullName>Fruits</fullName>
            </value>
            <value>
                <fullName>Electronics</fullName>
            </value>
            <value>
                <fullName>Gift</fullName>
            </value>
            <value>
                <fullName>Shopping</fullName>
            </value>
            <value>
                <fullName>Personal care</fullName>
            </value>
            <value>
                <fullName>Mobile Recharge</fullName>
            </value>
            <value>
                <fullName>Investment</fullName>
            </value>
            <value>
                <fullName>Medicines</fullName>
            </value>
            <value>
                <fullName>Cleaning</fullName>
            </value>
            <value>
                <fullName>Gas</fullName>
            </value>
            <value>
                <fullName>Electricity</fullName>
            </value>
            <value>
                <fullName>Tourism</fullName>
            </value>
            <value>
                <fullName>Food</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
                <default>true</default>
                <label>Others</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Expense__c/fields/Expense_Date__c.field-meta.xml
<CustomField>
    <fullName>Expense_Date__c</fullName>
    <defaultValue>Today()</defaultValue>
    <description>Date of the Expense</description>
    <label>Expense Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Expense__c/fields/Expense_on__c.field-meta.xml
<CustomField>
    <fullName>Expense_on__c</fullName>
    <defaultValue>&quot;Common&quot;</defaultValue>
    <inlineHelpText>Individual - Self expense
Pair - Sharing between 2 friends
Common - Common for all the users</inlineHelpText>
    <label>Expense on</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Individual</fullName>
            </value>
            <value>
                <fullName>Pair</fullName>
            </value>
            <value>
                <fullName>Common</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Expense__c/fields/Member__c.field-meta.xml
<CustomField>
    <fullName>Member__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Select the member</description>
    <label>Member</label>
    <referenceTo>User_Master__c</referenceTo>
    <relationshipLabel>Expenses</relationshipLabel>
    <relationshipName>Expenses</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Share__c/Share__c.object-meta.xml
<CustomObject>
    <description>Shares between user master</description>
    <label>Share</label>
    <nameField>
        <label>Shares Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shares</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Share__c/fields/Monthly_Expence__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Expence__c</fullName>
    <label>Monthly Expence</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Share__c/fields/Total_Expense__c.field-meta.xml
<CustomField>
    <fullName>Total_Expense__c</fullName>
    <label>Total Expense</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/User_Master__c/User_Master__c.object-meta.xml
<CustomObject>
    <description>List of user masters</description>
    <label>User Master</label>
    <nameField>
        <label>User Master Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>User Masters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Master__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <defaultValue>&quot;@gmail.com&quot;</defaultValue>
    <description>Email of the User</description>
    <label>Email</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/User_Master__c/fields/To_Get__c.field-meta.xml
<CustomField>
    <fullName>To_Get__c</fullName>
    <label>To Get</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/User_Master__c/fields/To_Pay__c.field-meta.xml
<CustomField>
    <fullName>To_Pay__c</fullName>
    <label>To Pay</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/User_Master__c/fields/Total_Amount_Shared__c.field-meta.xml
<CustomField>
    <fullName>Total_Amount_Shared__c</fullName>
    <label>Total Amount Shared</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/User_Master__c/fields/Total_Amount_Spent__c.field-meta.xml
<CustomField>
    <fullName>Total_Amount_Spent__c</fullName>
    <label>Total Amount Spent(Current Month)</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/User_Master__c/fields/Total_Expence__c.field-meta.xml
<CustomField>
    <fullName>Total_Expence__c</fullName>
    <label>Total Expence</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/Sharing_Details.cls
public class Sharing_Details {
   @auraEnabled
    public static List<Expense__c> getExp(){
        List<Expense__c> exp =  [SELECT Name, Member__c, Expense_on__c, Expense_Date__c, Category__c, Amount__c
                                FROM Expense__c
                                ];
        return exp;
    }
    
    @auraEnabled
    public static List<Expense__c> getExp1(){
        Date dat= Date.today();
        Integer mon = dat.month();
        List<Expense__c> exp =  [SELECT Name, Member__c, Expense_on__c, Expense_Date__c, Category__c, Amount__c
                                FROM Expense__c
                                WHERE CALENDAR_MONTH(Expense_Date__c) =: mon
                                ];
        return exp;
    }
     @auraEnabled
    public static Share__c getShare(){
        Date dat= Date.today();
        Integer mon = dat.month();
        Share__c Shar =     [SELECT Id,Name, Total_Expense__c, Monthly_Expence__c
                                FROM Share__c
                                WHERE CALENDAR_MONTH(createdDate) =: mon LIMIT 1
                                ];
        return Shar;
    }
    
    @auraEnabled
    public static List<User_Master__c> getUserMaster(){
        List<User_Master__c> usr =  [SELECT Id, Name, Total_Expence__c, Total_Amount_Shared__c, Total_Amount_Spent__c, To_Get__c, To_Pay__c, Email__c
                                    FROM User_Master__c
                                    ];
        return usr;
    }
    
    @AuraEnabled
    public static List<String> CatogeryValues(String fieldName, sObject objectName){
        system.debug('FildName :'+fieldName+ '\nobjectName :'+objectName);
        Schema.sObjectType objectType = objectName.getSObjectType();
        Schema.DescribeSObjectResult objectDescribe = objectType.getDescribe();
        System.debug('sObject Type :'+objectType+'\nDescribe : '+objectDescribe);
        Map<String,Schema.SObjectField> fieldMap = objectDescribe.fields.getMap();
        
        List<String> options = new List<String>();
        List<Schema.PicklistEntry> values = fieldMap.get(fieldName).getDescribe().getPickListValues();
        System.debug('Picklist values SChema.entry :'+values+'\nFieldmap of Object Describe : '+fieldMap);
        for(Schema.PicklistEntry opts: values){
            options.add(opts.getValue());
        }
        system.debug('Options : '+options);
        return options;
    }
    
    @AuraEnabled
    public static String SaveExpense(Expense__c Exp, String usr){
        String responses;
        
        DateTime dat = System.now();
        
        User_Master__c expUsr = [SELECT Id from User_Master__c WHERE Name =: usr];
        Exp.Member__c = expUsr.Id;
            
        if(Exp.Name == null){
        	Exp.Name = Exp.Category__c + ' Expense - '+dat.format('MMMM d, YYYY HH:mm');    
        }
        Date  ExpDate = Date.valueOf(Exp.Expense_Date__c);
        if(ExpDate != null){
            Exp.Expense_Date__c = ExpDate;
        }else{
            Exp.Expense_Date__c = System.today();
        }
        try{
            insert Exp;
            system.debug('Successfull : Expense - '+Exp);    
            responses = 'Success';
        }catch(Exception ex){
            responses = ex.getMessage();
        }
        return responses;
    }
}