force-app/main/default/objects/Expense__c/Expense__c.object-meta.xml
<CustomObject>
    <description>Expenses everyday</description>
    <label>Expense</label>
    <nameField>
        <label>Expence Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Expenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Expense__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <description>The Amount or Sum Spent on the Expense</description>
    <label>Amount</label>
    <precision>7</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Expense__c/fields/Bank_Name__c.field-meta.xml
<CustomField>
    <fullName>Bank_Name__c</fullName>
    <label>Bank Name</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Payment_Method__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>HDFC Bank</fullName>
            </value>
            <value>
                <fullName>Kotak Mahindra Bank</fullName>
            </value>
            <value>
                <fullName>State Bank of India</fullName>
            </value>
            <value>
                <fullName>Syndicate Bank</fullName>
            </value>
            <value>
                <fullName>Axis Bank</fullName>
            </value>
            <value>
                <fullName>Standard Charted Bank</fullName>
            </value>
            <value>
                <fullName>ICICI Bank</fullName>
            </value>
            <value>
                <fullName>Canara Bank</fullName>
            </value>
            <value>
                <fullName>Sounth Indian Bank</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Expense__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <description>Category of expense</description>
    <inlineHelpText>Select a specific Category, If not listed please select other and add comments.</inlineHelpText>
    <label>Category</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Rent</fullName>
            </value>
            <value>
                <fullName>Advance</fullName>
            </value>
            <value>
                <fullName>Vegetables</fullName>
            </value>
            <value>
                <fullName>Non Veg</fullName>
            </value>
            <value>
                <fullName>Dairy Eggs Batter</fullName>
            </value>
            <value>
                <fullName>Internet/Wi-Fi</fullName>
            </value>
            <value>
                <fullName>Water</fullName>
            </value>
            <value>
                <fullName>Groceries</fullName>
            </value>
            <value>
                <fullName>Bike</fullName>
            </value>
            <value>
                <fullName>Snacks</fullName>
            </value>
            <value>
                <fullName>Fruits</fullName>
            </value>
            <value>
                <fullName>Electronics</fullName>
            </value>
            <value>
                <fullName>Gift</fullName>
            </value>
            <value>
                <fullName>Shopping</fullName>
            </value>
            <value>
                <fullName>Personal care</fullName>
            </value>
            <value>
                <fullName>Mobile Recharge</fullName>
            </value>
            <value>
                <fullName>Investment</fullName>
            </value>
            <value>
                <fullName>Medicines</fullName>
            </value>
            <value>
                <fullName>Cleaning</fullName>
            </value>
            <value>
                <fullName>Gas</fullName>
            </value>
            <value>
                <fullName>Electricity</fullName>
            </value>
            <value>
                <fullName>Tourism</fullName>
            </value>
            <value>
                <fullName>Food</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
                <default>true</default>
                <label>Others</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Expense__c/fields/Comments__c.field-meta.xml
<CustomField>
    <fullName>Comments__c</fullName>
    <defaultValue>&quot;No Comments&quot;</defaultValue>
    <label>Comments</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Expense__c/fields/Expense_Date__c.field-meta.xml
<CustomField>
    <fullName>Expense_Date__c</fullName>
    <defaultValue>Today()</defaultValue>
    <description>Date of the Expense</description>
    <label>Expense Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Expense__c/fields/Expense_on__c.field-meta.xml
<CustomField>
    <fullName>Expense_on__c</fullName>
    <defaultValue>&quot;Common&quot;</defaultValue>
    <inlineHelpText>Individual - Self expense
Pair - Sharing between 2 friends
Common - Common for all the users</inlineHelpText>
    <label>Expense on</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Individual</fullName>
            </value>
            <value>
                <fullName>Pair</fullName>
            </value>
            <value>
                <fullName>Common</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Expense__c/fields/Member__c.field-meta.xml
<CustomField>
    <fullName>Member__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Select the member</description>
    <label>Member</label>
    <referenceTo>User_Master__c</referenceTo>
    <relationshipLabel>Expenses</relationshipLabel>
    <relationshipName>Expenses</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Expense__c/fields/Payment_Method__c.field-meta.xml
<CustomField>
    <fullName>Payment_Method__c</fullName>
    <defaultValue>&quot;Cash&quot;</defaultValue>
    <label>Payment Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Card</fullName>
            </value>
            <value>
                <fullName>Cash</fullName>
            </value>
            <value>
                <fullName>Wallet</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Expense__c/fields/Shared_with__c.field-meta.xml
<CustomField>
    <fullName>Shared_with__c</fullName>
    <label>Shared with</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Expense_on__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Aravindh</fullName>
            </value>
            <value>
                <fullName>Tejas</fullName>
            </value>
            <value>
                <fullName>Yokesh</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Expense__c/fields/Wallet_Name__c.field-meta.xml
<CustomField>
    <fullName>Wallet_Name__c</fullName>
    <label>Wallet Name</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Payment_Method__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Paytm</fullName>
            </value>
            <value>
                <fullName>Zeta</fullName>
            </value>
            <value>
                <fullName>Hungerbox</fullName>
            </value>
            <value>
                <fullName>Mobikwik</fullName>
            </value>
            <value>
                <fullName>Ola money</fullName>
            </value>
            <value>
                <fullName>Sodexo</fullName>
            </value>
            <value>
                <fullName>PayU money</fullName>
            </value>
            <value>
                <fullName>PhonePe</fullName>
            </value>
            <value>
                <fullName>Google Pay</fullName>
            </value>
            <value>
                <fullName>Gift card</fullName>
            </value>
            <value>
                <fullName>UPI</fullName>
            </value>
            <value>
                <fullName>Delivery wallet</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User_Master__c/User_Master__c.object-meta.xml
<CustomObject>
    <description>List of user masters</description>
    <label>User Master</label>
    <nameField>
        <label>User Master Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>User Masters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Master__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <defaultValue>&quot;@gmail.com&quot;</defaultValue>
    <description>Email of the User</description>
    <label>Email</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/User_Master__c/fields/Office_Mail__c.field-meta.xml
<CustomField>
    <fullName>Office_Mail__c</fullName>
    <label>Office Mail</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/User_Master__c/fields/Paid__c.field-meta.xml
<CustomField>
    <fullName>Paid__c</fullName>
    <label>Paid</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/User_Master__c/fields/Received__c.field-meta.xml
<CustomField>
    <fullName>Received__c</fullName>
    <description>Cash Received on Payments.</description>
    <label>Received</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/User_Master__c/fields/To_Get__c.field-meta.xml
<CustomField>
    <fullName>To_Get__c</fullName>
    <label>To Get</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/User_Master__c/fields/To_Pay__c.field-meta.xml
<CustomField>
    <fullName>To_Pay__c</fullName>
    <label>To Pay</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/User_Master__c/fields/Total_Amount_Shared__c.field-meta.xml
<CustomField>
    <fullName>Total_Amount_Shared__c</fullName>
    <label>Total Amount Shared</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/User_Master__c/fields/Total_Amount_Spent__c.field-meta.xml
<CustomField>
    <fullName>Total_Amount_Spent__c</fullName>
    <label>Total Amount Spent(Current Month)</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/User_Master__c/fields/Total_Expence__c.field-meta.xml
<CustomField>
    <fullName>Total_Expence__c</fullName>
    <label>Total Expence</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/Calculations.cls
public class Calculations {
    @AuraEnabled
    Public static void Tally(){
        List<Expense__c> Exps = [SELECT Id, Member__c, Category__c, Amount__c, Payment_Method__c, Expense_on__c, Comments__c, Shared_with__c, Bank_Name__c, Wallet_Name__c, Name, Expense_Date__c FROM Expense__c where Expense_on__c = 'Common'];
        List<User_Master__c> users = [SELECT Id, Name, Total_Expence__c, Total_Amount_Shared__c, Total_Amount_Spent__c, 
                                      To_Get__c, To_Pay__c, Paid__c, Received__c, Email__c
                                      FROM User_Master__c
                                     ];
        Map<Id,List<Expense__c>> userExp = new Map<Id,List<Expense__c>>();
        for(Expense__c exp : Exps){
            Id user = exp.Member__c;
            
            if(!userExp.containsKey(user)){
                userExp.put(user, new List<Expense__c>());
                userExp.get(user).add(exp);
            }else{
                userExp.get(user).add(exp);
            }
        }
        System.debug(' Map of Tasks : '+userExp);
        
        Map<Id,Decimal> individualExpense = new Map<Id,Decimal>();
        
        Decimal wholeExpTotal =0;
        
        for(User_Master__c usr : users){
            if(userExp.containsKey(usr.Id)){
                system.debug('Count of Expenses for '+usr.Name+' : '+userExp.get(usr.Id).size());   
                List<Expense__c> expenses = userExp.get(usr.Id); 
                Decimal  Total = 0;
                for(Integer i =0 ;i<expenses.size();i++){
                    Total = Total + expenses[i].Amount__c; 
                }
                individualExpense.put(usr.Id,Total);
                system.debug('Total Expense Amount: '+Total);
                wholeExpTotal = wholeExpTotal+ Total;
            }
            
        }
        
        for(User_Master__c talUser : users){
            System.debug(' wholeExpTotal '+ wholeExpTotal +' Average '+ (wholeExpTotal/3) +' - '+ individualExpense.get(talUser.Id)+ ' - ' + talUser.Paid__c +' + '+ talUser.Received__c+ ' - '+ talUser.To_Pay__c + ' + '+talUser.To_Get__c);
            Decimal talSum = (((wholeExpTotal/users.size()) - individualExpense.get(talUser.Id) - talUser.Paid__c) + talUser.Received__c )+ talUser.To_Get__c -talUser.To_Pay__c;
			System.debug('Loss Calculation for '+talUser.Name +' - talSum : Rs.'+talSum);
            if(talSum <= 1 && talSum >= -1){
            	System.debug(talUser.Name+' account has been \"Tallied\"');    
            }else{
                System.debug(talUser.Name+' account has been been \"Failed\" !!!');    
            }       
        }
    }
    Public static void sendEmail(Id user){
        User_Master__c taskUser = [SELECT Name, Email__c, Office_Mail__c, createdById
                                  FROM User_Master__c
                                  WHERE Id =: user];
        
        try{
            List<Messaging.SingleEmailMessage> mails =new List<Messaging.SingleEmailMessage>(); 
            
            EmailTemplate guardRailApproved = [SELECT Id, Name, Body, HtmlValue 
                                               FROM EmailTemplate where developerName = 'Open_Tasks'];
            //system.debug('templateId'+templateId);
            //system.debug('Body of Email'+guardRailApproved.Body);
            //system.debug('HTML Value of Email'+guardRailApproved.HtmlValue);
            Messaging.SingleEmailMessage sendPreApprMail = new Messaging.SingleEmailMessage();
            String[] sendingTo = new String[]{};
            String[] sendingCc = new String[]{};    
            sendingTo.add(taskUser.Email__c);
            sendingTo.add(taskUser.Office_Mail__c);
            system.debug('sender email id'+sendingTo);
            sendPreApprMail.setToAddresses(sendingTo);
            sendPreApprMail.setTemplateId(guardRailApproved.Id);
            //sendPreApprMail.setOrgWideEmailAddressId(taskUser.Office_Mail__c); 
            sendPreApprMail.setSaveAsActivity(false);
            sendPreApprMail.setTargetObjectId(taskUser.createdById);
            sendPreApprMail.setWhatId(taskUser.Id);
            mails.add(sendPreApprMail);
            Messaging.sendEmail(mails);
        
        }catch(exception ex){
            system.debug('Mail Failed with Message : '+ex.getMessage()); 
        }
    }

}