force-app/main/default/objects/Expense__c/Expense__c.object-meta.xml
<CustomObject>
    <description>Expenses everyday</description>
    <label>Expense</label>
    <nameField>
        <label>Expence Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Expenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Expense__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <description>The Amount or Sum Spent on the Expense</description>
    <label>Amount</label>
    <precision>7</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Expense__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <description>Category of expense</description>
    <inlineHelpText>Select a specific Category, If not listed please select other and add comments.</inlineHelpText>
    <label>Category</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Rent</fullName>
            </value>
            <value>
                <fullName>Advance</fullName>
            </value>
            <value>
                <fullName>Vegetables</fullName>
            </value>
            <value>
                <fullName>Non Veg</fullName>
            </value>
            <value>
                <fullName>Dairy Eggs Batter</fullName>
            </value>
            <value>
                <fullName>Internet/Wi-Fi</fullName>
            </value>
            <value>
                <fullName>Water</fullName>
            </value>
            <value>
                <fullName>Groceries</fullName>
            </value>
            <value>
                <fullName>Bike</fullName>
            </value>
            <value>
                <fullName>Snacks</fullName>
            </value>
            <value>
                <fullName>Fruits</fullName>
            </value>
            <value>
                <fullName>Electronics</fullName>
            </value>
            <value>
                <fullName>Gift</fullName>
            </value>
            <value>
                <fullName>Shopping</fullName>
            </value>
            <value>
                <fullName>Personal care</fullName>
            </value>
            <value>
                <fullName>Mobile Recharge</fullName>
            </value>
            <value>
                <fullName>Investment</fullName>
            </value>
            <value>
                <fullName>Medicines</fullName>
            </value>
            <value>
                <fullName>Cleaning</fullName>
            </value>
            <value>
                <fullName>Gas</fullName>
            </value>
            <value>
                <fullName>Electricity</fullName>
            </value>
            <value>
                <fullName>Tourism</fullName>
            </value>
            <value>
                <fullName>Food</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
                <default>true</default>
                <label>Others</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Expense__c/fields/Comments__c.field-meta.xml
<CustomField>
    <fullName>Comments__c</fullName>
    <defaultValue>&quot;No Comments&quot;</defaultValue>
    <label>Comments</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Expense__c/fields/Expense_on__c.field-meta.xml
<CustomField>
    <fullName>Expense_on__c</fullName>
    <defaultValue>&quot;Common&quot;</defaultValue>
    <inlineHelpText>Individual - Self expense
Pair - Sharing between 2 friends
Common - Common for all the users</inlineHelpText>
    <label>Expense on</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Individual</fullName>
            </value>
            <value>
                <fullName>Pair</fullName>
            </value>
            <value>
                <fullName>Common</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Expense__c/fields/Member__c.field-meta.xml
<CustomField>
    <fullName>Member__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Select the member</description>
    <label>Member</label>
    <referenceTo>User_Master__c</referenceTo>
    <relationshipLabel>Expenses</relationshipLabel>
    <relationshipName>Expenses</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Expense__c/fields/Payment_Method__c.field-meta.xml
<CustomField>
    <fullName>Payment_Method__c</fullName>
    <defaultValue>&quot;Cash&quot;</defaultValue>
    <label>Payment Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Card</fullName>
            </value>
            <value>
                <fullName>Cash</fullName>
            </value>
            <value>
                <fullName>Wallet</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Loan_and_Dues__c/Loan_and_Dues__c.object-meta.xml
<CustomObject>
    <label>Loan and Dues</label>
    <nameField>
        <displayFormat>Dues-{000}</displayFormat>
        <label>Dues Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loans and Dues</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Loan_and_Dues__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>8</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Loan_and_Dues__c/fields/Comments__c.field-meta.xml
<CustomField>
    <fullName>Comments__c</fullName>
    <label>Comments / Reason</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Loan_and_Dues__c/fields/Due_type__c.field-meta.xml
<CustomField>
    <fullName>Due_type__c</fullName>
    <defaultValue>&quot;Owe to&quot;</defaultValue>
    <label>Due type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Owe to</fullName>
            </value>
            <value>
                <fullName>Pending with</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Loan_and_Dues__c/fields/Paid_date__c.field-meta.xml
<CustomField>
    <fullName>Paid_date__c</fullName>
    <defaultValue>Today()</defaultValue>
    <label>Paid date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Loan_and_Dues__c/fields/Person_Name__c.field-meta.xml
<CustomField>
    <fullName>Person_Name__c</fullName>
    <label>Person Name</label>
    <referenceTo>User_Master__c</referenceTo>
    <relationshipLabel>Loans and Dues</relationshipLabel>
    <relationshipName>Loans_and_Dues</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Loan_and_Dues__c/fields/Secondary_User__c.field-meta.xml
<CustomField>
    <fullName>Secondary_User__c</fullName>
    <label>Secondary User</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Loan_and_Dues__c/fields/Settled_date__c.field-meta.xml
<CustomField>
    <fullName>Settled_date__c</fullName>
    <label>Settled Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Loan_and_Dues__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&quot;Pending&quot;</defaultValue>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment__c/Payment__c.object-meta.xml
<CustomObject>
    <label>Payment</label>
    <nameField>
        <displayFormat>Payment-{0000}</displayFormat>
        <label>Pay Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment__c/fields/Comments__c.field-meta.xml
<CustomField>
    <fullName>Comments__c</fullName>
    <defaultValue>&quot;Please verify&quot;</defaultValue>
    <label>Comments</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Pay_to__c.field-meta.xml
<CustomField>
    <fullName>Pay_to__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Pay to</label>
    <referenceTo>User_Master__c</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Payment_Method__c.field-meta.xml
<CustomField>
    <fullName>Payment_Method__c</fullName>
    <defaultValue>&quot;Cash&quot;</defaultValue>
    <label>Payment Method</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cash</fullName>
            </value>
            <value>
                <fullName>Card</fullName>
            </value>
            <value>
                <fullName>Wallet</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&quot;Pending&quot;</defaultValue>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Successful</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Wallet_From__c.field-meta.xml
<CustomField>
    <fullName>Wallet_From__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Wallet From</label>
    <referenceTo>User_Master__c</referenceTo>
    <relationshipLabel>Payments (Wallet From)</relationshipLabel>
    <relationshipName>Payments1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User_Master__c/User_Master__c.object-meta.xml
<CustomObject>
    <description>List of user masters</description>
    <label>User Master</label>
    <nameField>
        <label>User Master Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>User Masters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Master__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <defaultValue>&quot;@gmail.com&quot;</defaultValue>
    <description>Email of the User</description>
    <label>Email</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/User_Master__c/fields/Office_Mail__c.field-meta.xml
<CustomField>
    <fullName>Office_Mail__c</fullName>
    <label>Office Mail</label>
    <type>Email</type>
</CustomField>

force-app/main/default/classes/SendEmail.cls
public class SendEmail {
    public static PageReference sendingEmail(Payment__c pEmail){
        String uId1= pEmail.Wallet_From__c;
        String uId2= pEmail.Pay_to__c;
        User_Master__c otherUser =[SELECT Id, Name, Email__c
                                   FROM User_Master__c 
                                   WHERE ID !=: uId1 AND Name !=: uId2 LIMIT 1
                                  ];
        User_Master__c wFrom =[SELECT Id, Name, Email__c
                                   FROM User_Master__c 
                                   WHERE ID =: uId1 LIMIT 1
                                  ];
        User_Master__c pTo =[SELECT Id, Name, Email__c
                                   FROM User_Master__c 
                                   WHERE ID =: uId2 LIMIT 1
                                  ];
        Messaging.SingleEmailMessage seMail = new Messaging.SingleEmailMessage();
        Date Today = System.today();
        String toAddress=pEmail.Pay_to__r.Email__c;
        String ccAddress=otherUser.Email__c;	
        String bccAddress=pEmail.Wallet_From__r.Email__c;
        
        String[] sendingTo = new String[]{pTo.Email__c};
        
        if(pEmail.Pay_to__r.Name == 'Aravindh'){
            sendingTo.add('aravindhv04@gmail.com');    
        }
        
        if(pEmail.Pay_to__r.Name == 'Yokesh'){
            sendingTo.add('yokeshmohan1095@gmail.com');    
            sendingTo.add('aravindhv04@gmail.com'); 
        }
        
        if(pEmail.Pay_to__r.Name == 'Tejas'){
            sendingTo.add('tjtejo@gmail.com');
            sendingTo.add('aravindhv04@gmail.com'); 
        }
        
        String[] sendingTocAdd = new String[]{wFrom.Email__c};
            
        if(pEmail.Wallet_From__r.Name == 'Aravindh'){
            sendingTocAdd.add('aravindhv04@gmail.com');    
        }
        
        if(pEmail.Wallet_From__r.Name == 'Yokesh'){
            sendingTocAdd.add('yokeshmohan1095@gmail.com');    
            sendingTocAdd.add('aravindhv04@gmail.com'); 
        }
        
        if(pEmail.Wallet_From__r.Name == 'Tejas'){
            sendingTocAdd.add('tjtejo@gmail.com');
            sendingTocAdd.add('aravindhv04@gmail.com'); 
        }
        
        String[] sendingToBccAdd = new String[]{otherUser.Email__c};
		
		if(otherUser.Name == 'Aravindh'){
            sendingToBccAdd.add('aravindhv04@gmail.com');    
        }
        
        if(otherUser.Name == 'Yokesh'){
            sendingToBccAdd.add('yokeshmohan1095@gmail.com');    
            sendingToBccAdd.add('aravindhv04@gmail.com'); 
        }
        
        if(otherUser.Name == 'Tejas'){
            sendingToBccAdd.add('tjtejo@gmail.com');
            sendingToBccAdd.add('aravindhv04@gmail.com'); 
        }           
        seMail.setToAddresses(sendingTo);
        seMail.setCcAddresses(sendingTocAdd);
        seMail.emailPriority = 'High';
        
        seMail.setSubject('Monthly Expense - Cash Received ');
        seMail.setPlainTextBody('Hello '+pTo.Name+'!\n \t You have received Rs.'+pEmail.Amount__c+' from '+wFrom.Name+'. Please verify your \'ToGet\' amount feild and Approve once you have received the Amount'+'\n\n Sender Comments: '+pEmail.Comments__c+'\n\nAmount\t\t\t:\t'+pEmail.Amount__c+'\nPayment method:\t'+pEmail.Payment_Method__c+'\nSent date\t\t:\t'+Today+'\n\n\nRegards,\nSalesforce Developer\n'+wFrom.Name+'\n'+wFrom.Email__c+'To login:\t https://login.salesforce.com or https://aravindhapps-dev-ed.lightning.force.com');
        Messaging.sendEmail(new Messaging.SingleEmailMessage[] {seMail});
        return null;
    }
    
    public static PageReference sendEmailOnExpenceCreation(Expense__c exp){
        //Spending User
        String uId1= exp.Member__c;
        
        List<User_Master__c> otherUser =[SELECT Id, Name, Email__c
                                   FROM User_Master__c 
                                   WHERE ID !=: uId1 LIMIT 2
                                  ];
        User_Master__c expUser =[SELECT Id, Name, Email__c
                                   FROM User_Master__c 
                                   WHERE ID =: uId1 LIMIT 1
                                  ];
        
        Messaging.SingleEmailMessage seMail = new Messaging.SingleEmailMessage();
        
        Date Today = System.today();
        decimal share = (exp.Amount__c/3).setScale(2);
        decimal toReceive = (exp.Amount__c-share).setScale(2);
        String[] sendingTo = new String[]{expUser.Email__c};
        String[] sendingTocAdd = new String[]{otherUser[0].Email__c,otherUser[1].Email__c};
        
		
		seMail.setToAddresses(sendingTo);
        seMail.setCcAddresses(sendingTocAdd);
        seMail.emailPriority = 'High';
        
        seMail.setSubject('New Expense for '+expUser.Name);
        seMail.setPlainTextBody('Hello '+expUser.Name+'!\n \t You have added an Expense \''+exp.Name+'\' of Rs.'+exp.Amount__c+'\nYou need to receive Rs.'+toReceive+' from '+otherUser[0].Name+' and '+otherUser[1].Name+'.\n\nDetails\n=======\n'+'Spent On\t\t:\t'+exp.Category__c+'\nExpence Date\t  :\t'+Today+'\nSharing type\t  :\t'+exp.Expense_on__c+'\nPayment method\t  :\t'+exp.Payment_Method__c+'\n\nSharing Details\n---------------------\n\t'+expUser.Name+'		:\t'+Share+'\n\t'+otherUser[0].Name+'		:\t'+share+'\n\t'+otherUser[1].Name+'		\t:\t'+Share+'\n\n----------------\n Sender Comments: '+exp.Comments__c+'\n--------------------\n\n\nRegards,\nSalesforce Developer\n'+expUser.Name+'\n'+expUser.Email__c+'\n\n\nTo login:\t https://login.salesforce.com or https://aravindhapps-dev-ed.lightning.force.com');
        Messaging.sendEmail(new Messaging.SingleEmailMessage[] {seMail});
        return null;
    }
    public static PageReference sendEmailOnExpenceDeletion(Expense__c exp){
        String uId1= exp.Member__c;
        
        List<User_Master__c> otherUser =[SELECT Id, Name, Email__c
                                         FROM User_Master__c 
                                         WHERE ID !=: uId1 LIMIT 2];
        User_Master__c expUser =[SELECT Id, Name, Email__c
                                 FROM User_Master__c 
                                 WHERE ID =: uId1 LIMIT 1];
        
        Messaging.SingleEmailMessage seMail = new Messaging.SingleEmailMessage();
        
        Date Today = System.today();
        decimal share = (exp.Amount__c/3).setScale(2);
        decimal toReceive = (exp.Amount__c-share).setScale(2);
        String[] sendingTo = new String[]{expUser.Email__c};
        String[] sendingTocAdd = new String[]{otherUser[0].Email__c,otherUser[1].Email__c};
        
		
		seMail.setToAddresses(sendingTo);
        seMail.setCcAddresses(sendingTocAdd);
        seMail.emailPriority = 'High';
        
        seMail.setSubject('Expense Deletion for '+expUser.Name);
        seMail.setPlainTextBody('Hello '+expUser.Name+'!\n \tYour expense of \''+exp.Name+'\' on '+ exp.Category__c+' of Rs.'+exp.Amount__c+' has been deleted successfully. Cash changes will be reverted back. Please Verify.\n\nRegards,\nSalesforce'+'\n\n\nTo login:\t https://login.salesforce.com or https://aravindhapps-dev-ed.lightning.force.com');
        Messaging.sendEmail(new Messaging.SingleEmailMessage[] {seMail});
        
        return null;
    }
    
    public static PageReference sendEmailOnSharesRefresh(){
        List<User_Master__c> allUsers =[SELECT Id, Name, Email__c, Office_Mail__c
                                        FROM User_Master__c LIMIT 3
                                       ];
        Date Today = System.today();
        
        Messaging.SingleEmailMessage seMail = new Messaging.SingleEmailMessage();
        
        String[] sendingTo = new String[]{};
            
        for(User_Master__c usr: allUsers){
        	sendingTo.add(usr.Email__c);
            sendingTo.add(usr.Office_Mail__c);
        }
        seMail.setToAddresses(sendingTo);
        seMail.emailPriority = 'High';
        seMail.setSubject('Monthly Shares Refresh');
        seMail.setPlainTextBody('Hello All!,\n\tYour shares for this month has been refreshed and created Today ie.'+Today+' a new share record. Please Verify!\n\nRegards,\nSalesforce\n\n\nTo login:\t https://login.salesforce.com or https://aravindhapps-dev-ed.lightning.force.com');
        Messaging.sendEmail(new Messaging.SingleEmailMessage[] {seMail});

        return null;
    }
    public static PageReference sendACleaningReminder(){
        //Spending User
        List<User_Master__c> allUser =[SELECT Id, Name, Email__c
                                       FROM User_Master__c 
                                      ];
        
        
        Messaging.SingleEmailMessage seMail = new Messaging.SingleEmailMessage();
        
        
        String[] sendingTo = new String[]{allUser[0].Email__c,allUser[1].Email__c,allUser[2].Email__c};
        String[] sendingTocAdd = new String[]{'furiousflamesaravindh@gmail.com'};
        
		
		seMail.setToAddresses(sendingTo);
        seMail.setCcAddresses(sendingTocAdd);
        seMail.emailPriority = 'High';
        
        seMail.setSubject('Weekly Cleaning Reminder!!!');
        seMail.setPlainTextBody('Hello All, \n\t Gentle Reminder to clean Toilet and Mob the floor. Please Update completed If you have already done \n\nRegards, BGP Residence \nbgpresidence@home.com\n\n\nTo login:\t https://login.salesforce.com or https://aravindhapps-dev-ed.lightning.force.com');
        Messaging.sendEmail(new Messaging.SingleEmailMessage[] {seMail});
        return null;
    }
    
    //Rent - Send Email reminder
    public static PageReference sendRentEmailReminder(Id userId){
        List<User_Master__c> allUser =[SELECT Id, Name, Email__c
                                       FROM User_Master__c
                                       WHERE Id !=: userId	];
        Messaging.SingleEmailMessage seMail = new Messaging.SingleEmailMessage();
        
        
        String[] sendingTo = new String[]{allUser[0].Email__c,allUser[1].Email__c};
        String[] sendingTocAdd = new String[]{'furiousflamesaravindh@gmail.com'};
        
		
		seMail.setToAddresses(sendingTo);
        seMail.setCcAddresses(sendingTocAdd);
        seMail.emailPriority = 'High';
        seMail.setSubject('Rent Reminder!!!');
        seMail.setPlainTextBody('Hello Aravindh and Tejas, \n\t Gentle Reminder to send the \'Rent\' amount or remaining Amount of User Master to Yokesh without fail. Please Ignore if it had been done already.\n\nRegards, BGP Residence \nbgpresidence@home.com\n\n\nTo login:\t https://login.salesforce.com or https://aravindhapps-dev-ed.lightning.force.com');
        Messaging.sendEmail(new Messaging.SingleEmailMessage[] {seMail});
        return null;
    }
    
    //Loan and Dues Reminder Mail
    public static PageReference DueAmountReminder(Id loanId){
        User_Master__c userAravindh =[SELECT Id, Name, Email__c
                                      FROM User_Master__c
                                      WHERE Name = 'Aravindh'
                                     ];
        Loan_and_Dues__c loan = [SELECT Id, Person_Name__c, Due_type__c, Amount__c, Paid_date__c, Due_Date__c, Status__c, Comments__c, Secondary_User__c, Settled_date__c 
                                 FROM Loan_and_Dues__c
                                 WHERE Id =: loanId];
        
        
        Messaging.SingleEmailMessage seMail = new Messaging.SingleEmailMessage();
        
        
        String[] sendingTo = new String[]{userAravindh.Email__c};
        seMail.setToAddresses(sendingTo);
        String dueString;
        String paidDate = loan.Paid_date__c.format();
        if(loan.Due_type__c == 'Owe to' ){
            dueString = ' which is \'Pending\' with ';
        	seMail.setSubject('Loan and Dues! Pending Amount with your Friend '+ loan.Secondary_User__c);   
        }else if(loan.Due_type__c == 'Pending with' ){
            dueString = ' which you \'Owe\' to ';
            seMail.setSubject('Loan and Dues! Need to Pay your Friend '+loan.Secondary_User__c );  
        }
        seMail.emailPriority = 'High';
        seMail.setPlainTextBody('Hi '+userAravindh.Name+', \n\t Gentle Reminder to process the Due amount of Rs.'+loan.Amount__c+dueString+loan.Secondary_User__c+'. Transaction date '+paidDate+'.'+'\n\nRegards, \nSalesforce\n\n\nTo login:\t https://login.salesforce.com or https://aravindhapps-dev-ed.lightning.force.com\n\n Go to Record: https://aravindhapps-dev-ed.lightning.force.com/one/one.app#/sObject/'+loan.Id+'/view');
        Messaging.sendEmail(new Messaging.SingleEmailMessage[] {seMail});
        return null;
    }
    
}